### ISSUE TITLE
No files on pypi for 0.1.1

### ISSUE THREAD

**Issue by rileywilddog** [a-tal/ddate#3]
Pip is unable to install the latest version, 0.1.1, because it's not listed on https://pypi.org/simple/ddate/ , which is presumably because there are no files available for that version on pypi (https://pypi.org/project/ddate/0.1.1/#files).
Thanks!

**Comment by a-tal** [comment]
thanks for bringing this up. pypi seems to of gotten itself into a weird state. I tried to upload `0.1.1` to pypi directly via twine but it was saying the file was already there, which it wasn't.

anyway, fixed up some things with the pypi publishing on travis, tagged a `0.1.2` version, seems to be good now.

thanks again
